# Generated by Django 4.1.7 on 2023-03-08 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.IntegerField(db_index=True, verbose_name='Server CarID')),
                ('name', models.CharField(max_length=255, verbose_name='Car name')),
                ('car_type', models.CharField(max_length=255, verbose_name='Car type')),
                ('position', models.CharField(max_length=255, verbose_name='Coordinates')),
                ('car_status', models.CharField(choices=[('LINKED', 'Linked'), ('FREE', 'Free'), ('DELETED', 'Deleted')], default='LINKED', max_length=10, verbose_name='Car Status')),
                ('last_linit_time', models.DateTimeField(verbose_name='Last init time')),
                ('deletion_time', models.DateTimeField(blank=True, verbose_name='Deletion time')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steam_id', models.IntegerField(db_index=True, unique=True, verbose_name='SteamID')),
                ('dayzname', models.CharField(max_length=255, verbose_name='DayZ nickname')),
                ('dayz_alt_names', models.TextField(blank=True, verbose_name='Alternate names')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(verbose_name='Action time')),
                ('action', models.CharField(max_length=255, verbose_name='Action')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dzllogparser.car', verbose_name='Car')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dzllogparser.player', verbose_name='Player')),
            ],
        ),
    ]
