# Generated by Django 4.1.7 on 2023-04-16 13:02

from django.db import migrations, models
from dzllogparser.models import Car


def forwards_func(apps, schema_editor):
    cars_list = Car.objects.filter(deletion_time__isnull=True)
    for car in cars_list:
        try:
            last_using_time = car.event_set.last().action_time
        except AttributeError:
            continue
        else:
            car.last_using_time = last_using_time
            car.save()

class Migration(migrations.Migration):

    dependencies = [
        ('dzllogparser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='last_using_time',
            field=models.DateTimeField(blank=True, null=True,
                                       verbose_name='Last using time'),
        ),
        migrations.RunPython(code=forwards_func,
                             reverse_code=migrations.RunPython.noop),
    ]
